#3.1数字的四舍五入

In [4]:
print(round(1.23, 1))
print(round(1.23, 0))
print(round(123, -1))
print(round(123, -2))

1.2
1.0
120
100


In [12]:
#舍入和格式化不要搞混
'value is {!s}'.format(1.235)
#如果要进行格式转换,去掉!s
'value is {:0.3f}'.format(1.235)


'value is 1.235'

#3.2执行精确的浮点数运算

In [21]:
a = 2.1
b = 4.2
c = a + b
print(c)
round(c,1)

6.300000000000001


6.3

In [22]:
#金融数据通常使用decimal
from decimal import  localcontext, Decimal
a = Decimal('1.3')
b = Decimal('1.7')
print(a/b)
with localcontext() as ctx:
    ctx.prec = 3
    print(a/b)

0.7647058823529411764705882353
0.765


#3.3数字格式化输出

In [24]:
x = 1234.56789

print(format(x, '0.2f'))
#往右或左调整在10个字符里
print(format(x, '>10.1f'))
print(format(x, '<10.1f'))

1234.57
    1234.6
1234.6    


In [39]:
#同时指定宽度和精度的一般形式是'[<>^]?width[,]?(.digits)?'
print('The value is {:,.2f}'.format(x))
#%不支持千位符,
print('The value is {%10.2f}'% x)

The value is 1,234.57
The value is {   1234.57}


#3.4二八十六进制整数

In [40]:
#bin\oct\hex
x = 1234
print(bin(x))
print(oct(x))
print(hex(x))


0b10011010010
0o2322
0x4d2


In [41]:
#如果不想输出前缀使用format
format(x, 'b')


'10011010010'

In [42]:
#不同进制转换为十进制整数
int('4d2', 16)


1234

#3.5字节到大整数的打包与解包

In [1]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
len(data)

16

In [3]:
#big和little指定字节顺序
#bytes解析为整数
x = int.from_bytes(data, 'little')
#大整数转为字符串
x.to_bytes(16, 'big')

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

#3.6复数的数学运算

In [3]:
#复数表示
a = complex(2, 4)
b = 3 - 5j
a,b

((2+4j), (3-5j))

In [5]:
#实部虚部共轭复数
print(a.real)
print(a.imag)
print(a.conjugate())

2.0
4.0
(2-4j)


In [11]:
#数学运算
a + b, a * b, format(a / b, '.2f'), abs(a) 

((5-1j), (26+2j), '-0.41+0.65j', 4.47213595499958)

In [12]:
#其他函数
import cmath
cmath.sin(a), cmath.cos(a), cmath.exp(a)

((24.83130584894638-11.356612711218174j),
 (-11.36423470640106-24.814651485634187j),
 (-4.829809383269385-5.5920560936409816j))

In [20]:
#numpy支持复数运算
import numpy as np
a = np.array([2+3j, 4+5j, 6-7j, 8+9j])
a, a+2, np.sin(a)

(array([2.+3.j, 4.+5.j, 6.-7.j, 8.+9.j]),
 array([ 4.+3.j,  6.+5.j,  8.-7.j, 10.+9.j]),
 array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
        -153.20827755-526.47684926j, 4008.42651446-589.49948373j]))

#标准math不会产生复数，要使用cmath
cmath.sqrt(-1)

#3.7无穷大与NaN

In [23]:
#使用float创建
float('inf'), float('-inf'), float('nan'), 


(inf, -inf, nan)

#3.8分数运算

In [25]:
from fractions import Fraction
a = Fraction(5, 4) #5/4
b = Fraction(7, 16)#7/16
print(a + b)
print(a * b)


27/16
35/64


In [29]:
c = a * b
c.numerator, c.denominator, float(c) # 分子/分母, 小数

(35, 64, 0.546875)

In [31]:
#小数转分数
Fraction(*3.75.as_integer_ratio())

Fraction(15, 4)

#3.9大型数组运算

In [23]:
#numpy与标准列表的区别
import numpy as np
x = [1, 2, 3, 4]
ax = np.array([1, 2, 3, 4])
y = [5, 6, 7, 8]
ay = np.array([5, 6, 7, 8])
print(x * 2, ax * 2)
print(x + y, ax + ay)
#标准列表不能直接+int和*list
print(ax + 1)
print(ax * ay)



[1, 2, 3, 4, 1, 2, 3, 4] [2 4 6 8]
[1, 2, 3, 4, 5, 6, 7, 8] [ 6  8 10 12]
[2 3 4 5]
[ 5 12 21 32]


In [20]:
def f(x):
    return 3 * x ** 2
#f = lambda x: 3*x**2
[f(x) for x in x], f(ax)

([3, 12, 27, 48], array([ 3, 12, 27, 48], dtype=int32))

In [21]:
#numpy提供了大量通用函数
np.sqrt(ax), np.cos(ax)

(array([1.        , 1.41421356, 1.73205081, 2.        ]),
 array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362]))

In [22]:
np.zeros(shape=(10000, 10000), dtype=float)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

#3.10矩阵与线性代数运算

In [30]:
#矩阵转置、逆、相乘
m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
n = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
m, m.T, m.I, m * n

(matrix([[ 1, -2,  3],
         [ 0,  4,  5],
         [ 7,  8, -9]]),
 matrix([[ 1,  0,  7],
         [-2,  4,  8],
         [ 3,  5, -9]]),
 matrix([[ 0.33043478, -0.02608696,  0.09565217],
         [-0.15217391,  0.13043478,  0.02173913],
         [ 0.12173913,  0.09565217, -0.0173913 ]]),
 matrix([[ 22,  14, -34],
         [ 35,  56, -25],
         [-56, -54, 142]]))

#3.11随机选择

In [42]:
import random
values = [1, 2, 3, 4 ,5, 6]
print(random.choice(values), ' ',random.sample(values, 2))
random.shuffle(values)
print(values)

1   [4, 2]
[2, 4, 1, 5, 6, 3]


In [50]:
#生成随机整数
#0|1, 0-1的浮点数
random.randint(0,1), random.random()

(1, 0.06294627569694178)

In [118]:
#N位随机位整数(2 ** N)
random.getrandbits(4)

2

In [119]:
#修改随机种子
random.seed()

#3.12基本日期与时间转换

In [122]:
from datetime import timedelta, datetime
a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
c.days, c.seconds,c.seconds/3600

(2, 37800, 10.5)

In [123]:
a = datetime(2012, 9, 23)
a + timedelta(days=10)

datetime.datetime(2012, 10, 3, 0, 0)

#3.13计算最后一个周五的日期

In [128]:
from datetime import timedelta, datetime
weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
'Friday', 'Saturday', 'Sunday']

def get_previous_byday(dayname, start_date=None):
    if start_date is None:
        start_date = datetime.today()
    day_num = start_date.weekday()
    day_num_target = weekdays.index(dayname)
    days_ago = (7 + day_num - day_num_target) % 7
    if days_ago == 0:
        days_ago = 7
    target_date = start_date - timedelta(days=days_ago)
    return target_date

datetime.today(), get_previous_byday('Monday'), \
get_previous_byday('Friday', datetime(2012,12,1))

(datetime.datetime(2020, 5, 18, 18, 57, 34, 305914),
 datetime.datetime(2020, 5, 11, 18, 57, 34, 305914),
 datetime.datetime(2012, 11, 30, 0, 0))

#3.14计算当前月份的日期范围

In [130]:
from datetime import datetime, date, timedelta
import calendar

def get_month_range(start_date=None):
    if start_date is None:
        start_date = date.today().replace(day=1)
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    end_date = start_date + timedelta(days=days_in_month)
    return (start_date, end_date)

a_day = timedelta(days=1)
first_day, last_day = get_month_range()
while first_day < last_day:
    print(first_day)
    first_day += a_day

In [135]:
#使用生成器给日期内置range函数
def date_range(start, stop, step):
    while start < stop:
        yield start
        start += step
        
for d in date_range(datetime(2020, 12, 30), datetime(2020, 12, 31), timedelta(hours=12)):
    print(d)

2020-12-30 00:00:00
2020-12-30 12:00:00


#3.15字符串转换为日期

In [138]:
text = '2012-09-20-12-20'
y = datetime.strptime(text, '%Y-%m-%d-%H-%M')
y

datetime.datetime(2012, 9, 20, 12, 20)

In [141]:
#我们可以自己实现
def parse_ymd(s):
    year_s, mon_s, day_s, hou_s, min_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

parse_ymd(text)


datetime.datetime(2012, 9, 20, 0, 0)

#3.16结合时区的日期操作

In [144]:
from pytz import timezone
d = datetime(2012, 12, 21, 9, 30, 0)
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

2012-12-21 09:30:00-06:00


In [145]:
#本地化后转换为别的地区
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print(bang_d)

2012-12-21 21:00:00+05:30
